### ISSUE TITLE
3.2.5

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim11#3]
Zar nebi prava bila na nivou grupe koje bi onda korisnici primili učlanjivanje u grupu. Vi kažete "taj isti korisnik doda i odredi im prava pristupa ". U tvari je opis malo konfuzan. 
Npr. grupa finansije ima pravo čitanja i pisanja na folder "finasije". grupa ima 10 korisnika i svi kao članovi grupe imaju pravo da čitaju i pišu. u taj folder.
pravo pristupa nije definisano

**Comment by dzemila** [comment]
Uradjeno malo drugacije

**Comment by deancupovic** [comment]
Ovo je u suštini poređenje RBAC i DAC (odnosno ACL - access control list). Mada vaša implementacija je varijanta DAC.
http://security.stackexchange.com/questions/346/what-is-the-difference-between-rbac-and-dac-acl
Primjer standardne role based kontrole pristupa:
Svi ljudi koji posjeduju pasoš BiH (članovi su grupe gradjani_BIH) imaju pravo ulaska u države šengena bez vize (jedna vrsta prava, npr. write). Svi ljudi koji posjeduju pasoš Iraka imaju pravo ulaska u države Šengena, ali uz posjedovanje vize (druga vrsta prava, npr. read). Prilikom ulaska u Šengen se pasošem potvrđuje pripadnost određenom državljanstvu (grupi) i na osnovu toga dozvoljava ulazak ili ne, sa vizom ili bez. Sve države Šengena dijele spisak država (grupa) koje imaju pravo ulaska sa ili bez vize.
Vaša implementacija je ovakva:
Svi ljudi koji su na spisku ljudi sa pravom ulaska u Šengen (grupa) mogu ući, ali uz provjeru Da li treba viza ili ne (npr. da li on ima pravo read/write). Dakle, čovjek prilikom ulaska u Šengen potvrđuje svoj identitet (ali ne i državljanstvo), pa se onda on traži na spisku svih ljudi sa pravom ulaska u Šengen da se odredi da li je na spisku i ako jeste da li mu treba viza ili ne. Sve države Šengena dijele spisak ljudi (pripadaju istoj "grupi").
Da, u vašem modelu je moguće da neki ljudi iz BiH ili Iraka mogu ući bez vize, a neki moraju imati vizu. Ali održavanje tog spiska je vrlo teško.
Zašto vaša implementacija nije standardni DAC? Zato što se prava pristupa definišu na nivou resursa (folderu ili fajlu), a ne, kao kod vas, na nivou grupe.
U principu vi definišete ACL na nivou grupe koja se onda dodjeljuje nekom folderu. Više foldera može imati tu istu ACL (tj. grupu i prava pristupa korisnika), ali je ta lista definisana za pojedinačnog korisnika, to jest grupa u smislu članstva u roli i grupi ne postoji. Vaša grupa je u stvari lista prava pristupa (ACL) pojedinačnih korisnika koja se može dijeliti između resursa.
Da li je to pogrešno? Nije. Da li je standardna implementacija? Nije. Da li je bolje ili lošije od RBAC? Nije, svaka implementacija ima svoje prednosti i mane. Zbog čega je nastala konfuzija? Zato što ste vi koristili pojam grupe (nešto što se standardno koristi u RBAC) i od toga napravili listu prava pristupa (ACL) koja se koristi u DAC.
Jasniji naziv vaše grupe bi bio resursi. Pa bio onda umjesto grupe "Finansije" imali resurs "finansijski resursi" i na nivou resursa bi definisala pojedinačna prava pristupa.

**Comment by esensar** [comment]
Ispravljeni ERD-ovi i klase.
