### ISSUE TITLE
Duplicirane/pogresne vrijednosti u tipu korisnika i pozicije u organizaciji kod dodavanja korisnika

### ISSUE THREAD

**Issue by mirzetb** [SoftverInzenjeringETFSA/SI2015Tim11#37]
Opis problema:
Podaci za izbor tipa korisnika i pozicije u organizaciji na formi za dodavanje korisnika nisu korektni. Kod tipa korisnika se pojavljuje vise instanci istog validnog tipa (Administrator i korisnik) kao i neke opcije koje prema specifikaciji nisu validne (naziv tipa). Slicna je situacija i kod pozicije u organizaciji.

Koraci za reproduciranje problema:
1. Pokrenuti LoginForma.java
2. Unijeti korisnicke podatke (root:root123)
3. Odabrati korisnici->dodavanje korisnika iz menija
4. Otvoriti sadrzaj opcija combobox-a za tip korisnika tj. poziciju u organizaciji

http://pokit.org/get/?095edf3918c5668350adb5aa7bca659c.jpg
http://pokit.org/get/?c3dce10018d1f9c469dfab22523fe799.jpg

Očekivani rezultat:
Validne i jedinstvene opcije izbora u vise navedenim komponentama.

**Comment by esinanovic2** [comment]
Problem je što su u bazi ostale vrijednosti koje su se koristile prilikom testiranja. Kada se očisti baza, neće više biti problem jer nema načina da se doda novi tip i nova pozicija za korisnike unutar aplikacije.

**Comment by mirzetb** [comment]
Nije da sam skeptican, ali mozete li postaviti skriptu koja cisti bazu ili je dovodi u neko poznato validno stanje?
