### ISSUE TITLE
Neslaganje ER dijagrama iz postavljene skripte sa onim iz dokumentacije 

### ISSUE THREAD

**Issue by avelic** [SoftverInzenjeringETFSA/SI2015Tim11#38]
Komponenta: ERD int .sql 
commitID: 7b117ff  3d90eb0 
![tim11](https://cloud.githubusercontent.com/assets/11328974/15301447/00cb8c78-1bae-11e6-8c14-f0f1f9684462.png)
![tim111](https://cloud.githubusercontent.com/assets/11328974/15301451/06b0f240-1bae-11e6-9094-26915c412252.png)

Dobijeni rezultat:
Neslaganje postavljenog ERD-a sa onim iz skripte
Očekivani rezultat:
Slaganje postavljenog ERD-a sa onim iz skripte

**Comment by esinanovic2** [comment]
Necemo mijenjati jer bi se u tom slučaju promijenila struktura programa, a već smo se oko ovog problema konsultovali s asistentom.
