### ISSUE TITLE
Na fromi za Login ne postoji dugme izlaz koje je navedeno u dizajnu UI 

### ISSUE THREAD

**Issue by avelic** [SoftverInzenjeringETFSA/SI2015Tim11#39]
Komonenta : LoginForma 
CommitID: 4877cb5  b07afa5  

Koraci za reproduciranje problema:
1. Pokrenuti LoginForma.java
2. Unijeti korisnicke podatke (root:root123)

Ocekivani Izlaz : Prikaz dugmeta za Izlaz

**Comment by esinanovic2** [comment]
Ispravljeno Commit ID:      6e5d255
