### ISSUE TITLE
Problemi sa formom za izmjenu korisnika

### ISSUE THREAD

**Issue by mirzetb** [SoftverInzenjeringETFSA/SI2015Tim11#40]
Opis:
Uslijed odabria korisnika koji se mijenja, njegove informacije se prikazuju u vidu tabele gdje se prikazuju neke infromacije koje nisu intuitivno jasne (tipa brojeva, 2, 3). Prema specifikaciji administrator ima pravo da mijenja sve osim korisnickog imena. Kada se pokusaju izmijeniti ove informacije (3, 2) dolazi do bacanja izuzetka. 

Koraci za reproduciranje problema:
1. Pokrenuti LoginForma.java
2. Unijeti korisnicke podatke (root:root123)
3. Odabrati korisnici->izmjena korisnika iz menija
4. Upisati nekog korisnika koji postoji u polje za unos i pretraziti 
5. Pokusati izmijeniti polja 3, 2 (sta god to bilo)

http://pokit.org/get/?07ee9de44d0c54d2617032bfdf2dad46.jpg

Ocekivani razultat:
Prikaz osobina korisnika koje se mogu mijenjati u prihvatljivijem formatu. Obraditi izuzetke.

**Comment by esinanovic2** [comment]
Ispravljeno.  CommitID: 8e2f7d2
