### ISSUE TITLE
Neslaganje formi sa specifikacijom dizajna

### ISSUE THREAD

**Issue by mirzetb** [SoftverInzenjeringETFSA/SI2015Tim11#41]
Opis:
U vezi sa issue #39, velika vecina (ako ne i sve) forme se ne slazu sa onima navedenim u specifikaciji dizajna (https://github.com/SoftverInzenjeringETFSA/SI2015Tim11/blob/master/Task%204/Dizajn%20UI.pdf). 
Npr. pocetni screen realni
http://pokit.org/get/?aed925eef19a416e6c67442dedde4ee9.jpg
vs. specifikacija
http://pokit.org/get/?ff383671e0537f0d6973c3aed0b5d097.jpg

Ocekivani rezultat:
Doslijednost specifikacije dizajna UI i realnog dizajna.

**Comment by esinanovic2** [comment]
Pošto je to problem sa SRS-om, to ne možemo promijeniti.
