### ISSUE TITLE
Grupna prava pristupa nad dokumentima

### ISSUE THREAD

**Issue by mirzetb** [SoftverInzenjeringETFSA/SI2015Tim11#42]
Opis:
Kako je navedeno u specifikaciji (3.2.6) i (3.2.7) administrator grupe moze svakom korisniku iz grupe dodijeliti/promijeniit/oduzeti prava nad pojedinim dokumentima. Ovakav vid dodjele prava nije omogucen kroz aplikaciju. Omogucena je jedino dodjela prava u odnosu na grupu.

Koraci za reproduciranje problema:
1. Pokrenuti LoginForma.java
2. Unijeti korisnicke podatke (root:root123)
3. Odabrati grupe->dodavanje tj. grupe->izmjena grupe iz menija

http://pokit.org/get/?b96d068b4113d86ae9ad89ed70162806.jpg

Ocekivano:
Moucnost manipulacije nad individualnim pravima korisnika u grupi.

**Comment by esinanovic2** [comment]
Ovo je u dogovoru sa asistentom promijenjeno, pa se neće ispravljati.
