### ISSUE TITLE
Zatvaranje forme "GlavnaForma"

### ISSUE THREAD

**Issue by mhadzic3** [SoftverInzenjeringETFSA/SI2015Tim11#44]
Komponenta: GlavnaForma

Opis problema:
Nakon klika na dugme "Izlaz" na meniju ili na dugme izlaza na formi zatvori se cijela aplikacija, ne vrati se na LoginForma.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Prijaviti se kao neki korisnik iz baze (npr. username:root, password:root123).
3. Kliknuti na dugme "Izlaz" u meniju forme ili na dugme izlaza na formi.

Dobijeni rezultat:
-Zatvorena je cijela aplikacija. Mora se ponovo pokrenuti aplikacija za prijavu nekog korisnika.

Očekivani rezlutat:
-Povratak na LoginForma.

**Comment by muhamed-smajevic** [comment]
Riješeno u 211fcb4b5ed695b57a5cfdafd9b2a06a02b55eb2
