### ISSUE TITLE
Nije urađena validacija datuma

### ISSUE THREAD

**Issue by avelic** [SoftverInzenjeringETFSA/SI2015Tim11#45]
Komponenta: DodavanjeKorisnika

CommintID :725959c 

Koraci za reproduciranje problema:
1.Pokrenuti LoginForma.java
2.Unijeti korisnicke podatke (root:root123)
3.Korisnici
4.Dodavanje korisnika

Dobijeni rezultat:
Moguće dodati korisnika sa datumom rođenja većim od trenutnog datuma
 Očekivani rezultat:
 Validran unos datuma

**Comment by esinanovic2** [comment]
Riješeno u 01baf30
