### ISSUE TITLE
Pregled izvjstaja ne daje nikakav efekat i nije defnisano kako se izvjestaji generisu

### ISSUE THREAD

**Issue by avelic** [SoftverInzenjeringETFSA/SI2015Tim11#47]
Komponenta: Glavna Forma
CommitID : 725959c 

Koraci za reproduciranje problema:
 1.Pokrenuti LoginForma.java
 2.Unijeti korisnicke podatke (root:root123)
 3.Izvjestaj

 Očekivani rezultat:
 Pregled Izvjestaja

**Comment by esensar** [comment]
Popravljeno ad443b5
