### ISSUE TITLE
Pregled zahtjeva i dodavanje zahtjeva nemaju nikakav odziv

### ISSUE THREAD

**Issue by mirzetb** [SoftverInzenjeringETFSA/SI2015Tim11#48]
Commit ID: 01baf30 
Opis:
Manipulacija zahtjevima nije implementirana. Nema povratne informacije prilikom pokusaja prikaza zahtjeva ili dodavanja zahtjeva.

Koraci za reproduciranje problema:
1. Pokrenuti LoginForma.java
2. Unijeti korisnicke podatke (root:root123)
3. Odabrati zahtjevi->pregled zahtjeva | dodavanje zahtjeva

Dobiveni rezultat:
Nista.
Ocekivani rezultat:
Pregled zahtjeva tj. mogucnost dodavanja novog zahtjeva ili neki drugi smisleni odziv.

**Comment by amirsabanovic** [comment]
Popravljeno.
