### ISSUE TITLE
Opcija menija  "Zahtjevi -> Dodavanje zahtjeva"   ne radi nista 

### ISSUE THREAD

**Issue by avelic** [SoftverInzenjeringETFSA/SI2015Tim11#50]
Komponenta: Glavna Forma
 CommitID :  717b6a3

Koraci za reproduciranje problema:
 1.Pokrenuti LoginForma.java
 2.Unijeti korisnicke podatke za korisnika 
 3.Zahtjevi -> Dodavanje zahtjeva

Dobijeni rezultat: 
Opcija ne radi nista 

Očekivani rezultat:
 Dodavanje zahtjeva

**Comment by esinanovic2** [comment]
Duplikat #48
